// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmxlxalshkmkwswdtaxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNteGx4YWxzaGtta3dzd2R0YXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjQwMDYsImV4cCI6MjA2NTk0MDAwNn0.nFYvpN3tkLfxJlbdZIFgvmj7IjhzDYB5fcQi9FZmf6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);